# Generated by Django 5.0.6 on 2024-05-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsmodel_alter_categorymodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='title',
            field=models.CharField(help_text='Напишите название продукта!', max_length=100),
        ),
    ]
