# Generated by Django 5.0.6 on 2024-05-30 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productsmodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categorymodel'),
        ),
    ]
